# Generated by Django 6.0.7 on 2026-07-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_complaint_complaintimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintimage',
            name='image',
        ),
        migrations.AddField(
            model_name='complaintimage',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
