# Generated by Django 6.0.7 on 2026-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_complaintimage_image_complaintimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('road_pothole', 'Road Pothole'), ('garbage', 'Garbage'), ('drainage', 'Drainage')], max_length=20),
        ),
    ]
