# Generated by Django 6.0.7 on 2026-08-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
