# Generated by Django 6.0.7 on 2026-08-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
